apiVersion: v1
kind: Service
metadata:
  name: youfie-crawler
  labels:
    app: youfie-crawler
    tier: backend
spec:
    ports:
    - port: 80
    selector:
      app: youfie-api
      tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: youfie-crawler
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: youfie-api
        tier: backend
    spec:
      containers:
        - image: gcr.io/youfie-983ce/github-trevorprater-youfie-crawler:9b12a78bd75bbaa5f5b099df41fc8b88910e1685
          name: web
          env:
            - name: GET_HOSTS_FROM
              value: dns

            # [END cloudsql_secrets]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      # [END volumes]
