apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: youfie-crawler
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: youfie-api
        tier: backend
    spec:
      containers:
        - image: gcr.io/youfie-983ce/github-trevorprater-youfie-crawler:dbaea768ba66ba152ed34a85c4ac5a09bf83ee19

          name: youfie-crawler-imgur
          env:
            - name: GET_HOSTS_FROM
              value: dns

            # [END cloudsql_secrets]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
      # [END volumes]
